version: '2'
services:
  web:
    build: .
    command: bundle exec puma -p 9292 -e development
    environment:
      - RETHINKDB_URL=rethinkdb://db/todo_development
      - RACK_ENV=development
    ports:
      - 9292:9292
  db:
    image: rethinkdb:latest
    ports:
      - 8080:8080
