test:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://localhost:27017/todo_test' %>
development:
  clients:
    default:
      database: todo_development
      hosts:
        - localhost:27017
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://localhost:27017/todo_production' %>
